# Generated by Django 3.1.1 on 2020-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='match/', verbose_name='Image')),
                ('team_name1', models.CharField(max_length=30, verbose_name='First Team Name')),
                ('team_country1', models.CharField(max_length=20, verbose_name='First Team Country')),
                ('score1', models.IntegerField(verbose_name='Score Team One')),
                ('score2', models.IntegerField(verbose_name='Score Team Two')),
                ('image2', models.ImageField(upload_to='match/', verbose_name='Image')),
                ('team_name2', models.CharField(max_length=30, verbose_name='Second Team Name')),
                ('team_country2', models.CharField(max_length=20, verbose_name='Second Team Country')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='player/', verbose_name='Image')),
                ('fname', models.CharField(max_length=15, verbose_name='First Name')),
                ('lname', models.CharField(max_length=15, verbose_name='Last Name')),
                ('birth', models.DateField(verbose_name='Date of Birth')),
                ('position', models.CharField(max_length=12, verbose_name='Position')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
