# Generated by Django 3.1.1 on 2020-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='match',
            name='image1',
            field=models.ImageField(upload_to='match/', verbose_name='Фото первой команды'),
        ),
        migrations.AlterField(
            model_name='match',
            name='image2',
            field=models.ImageField(upload_to='match/', verbose_name='Фото второй'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(verbose_name='Голов первой'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(verbose_name='Голово второй'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_country1',
            field=models.CharField(max_length=20, verbose_name='Страна первой команды'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_country2',
            field=models.CharField(max_length=20, verbose_name='Страна второй команды'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_name1',
            field=models.CharField(max_length=30, verbose_name='Название первой команды'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_name2',
            field=models.CharField(max_length=30, verbose_name='Название второй команды'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.DateField(verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fname',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='player/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lname',
            field=models.CharField(max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=12, verbose_name='Позиция'),
        ),
    ]
