# Generated by Django 3.1.1 on 2020-10-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_auto_20201007_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Игру', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрока', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голов первой'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голов второй'),
        ),
    ]
