# Generated by Django 3.1.1 on 2020-10-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20201008_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=265, verbose_name='Описание'),
        ),
    ]
