# Generated by Django 3.1.1 on 2020-10-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_auto_20201008_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_country1_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Страна первой команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_country1_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Страна первой команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_country2_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Страна второй команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_country2_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Страна второй команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_name1_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название первой команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_name1_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название первой команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_name2_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название второй команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_name2_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название второй команды'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_ru',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(max_length=265, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(max_length=265, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='player',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='player',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='player',
            name='fname_en',
            field=models.CharField(max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='player',
            name='fname_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='player',
            name='lname_en',
            field=models.CharField(max_length=15, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='player',
            name='lname_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='player',
            name='position_en',
            field=models.CharField(max_length=12, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='player',
            name='position_ru',
            field=models.CharField(max_length=12, null=True, verbose_name='Позиция'),
        ),
    ]
