# Generated by Django 3.1.1 on 2020-10-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0005_auto_20201008_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_country1_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_country1_ru',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_country2_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_country2_ru',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_name1_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_name1_ru',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_name2_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_name2_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='player',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='player',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fname_en',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fname_ru',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lname_en',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lname_ru',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_ru',
        ),
    ]
